export enum HomeTypes {
  HANDLE_MODALS = 'HANDLE_MODALS',
  LOAD_DATAFLOWS = 'LOAD_DATAFLOWS',
  LOAD_DATAFLOWS_AMOUNT = 'LOAD_DATAFLOWS_AMOUNT',
  ON_CHANGE_VIEW = 'ON_CHANGE_VIEW',
  SET_LOADING_STATUS = 'SET_LOADING_STATUS'
}
